
export const SORT_POSTS = 'SORT_POSTS';
export const SHOW_DETAIL = 'SHOW_DETAIL';
export const FETCHED_RESULTS = 'FETCHED_RESULTS';
export const DETAILED_VIEW = 'DETAILED_VIEW';
export const SET_LOCAL = 'SET_LOCAL';
export const SORT_POSTS_BY_WATCHING='SORT_POSTS_BY_WATCHING';
export const SORT_POSTS_BY_OWNER='SORT_POSTS_BY_OWNER';
export const FETCH_TOPICS = 'FETCH_TOPICS';
export const SORT_POSTS_BY_FORKS= 'SORT_POSTS_BY_FORKS';
export const SORT_POSTS_BY_SCORE= 'SORT_POSTS_BY_SCORE';
export const SET_SORT_FILTER= 'SET_SORT_FILTER';