
export const SORT_POSTS = 'SORT_POSTS';
export const SHOW_DETAIL = 'SHOW_DETAIL';
export const FETCHED_RESULTS = 'FETCHED_RESULTS';
export const DETAILED_VIEW = 'DETAILED_VIEW';
export const SET_LOCAL = 'SET_LOCAL';
export const SORT_POSTS_BY_WATCHING='SORT_POSTS_BY_WATCHING';
export const SORT_POSTS_BY_OWNER='SORT_POSTS_BY_OWNER';